"""Switch embedding vector from 1536 (OpenAI) to 1024 (Bedrock Titan V2).

Revision ID: 003
Revises: 002
Create Date: 2026-03-20

Notes:
  - Existing embeddings are dropped and must be re-generated by re-ingesting.
  - Titan Text Embeddings V2 supports 256 / 512 / 1024 dims; 1024 is default.
  - The HNSW index is recreated for the new dimensionality.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector

revision: str = "003"
down_revision: Union[str, None] = "002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

OLD_DIMS = 1536
NEW_DIMS = 1024


def upgrade() -> None:
    # Drop old index first (cannot alter vector dims in-place)
    op.execute("DROP INDEX IF EXISTS ix_chunks_embedding")

    # Replace the embedding column
    op.drop_column("chunks", "embedding")
    op.add_column("chunks", sa.Column("embedding", Vector(NEW_DIMS), nullable=True))

    # Recreate HNSW index for cosine similarity search
    op.execute("""
        CREATE INDEX ix_chunks_embedding
        ON chunks
        USING hnsw (embedding vector_cosine_ops)
        WITH (m = 16, ef_construction = 64)
    """)


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_chunks_embedding")
    op.drop_column("chunks", "embedding")
    op.add_column("chunks", sa.Column("embedding", Vector(OLD_DIMS), nullable=True))
    op.execute("""
        CREATE INDEX ix_chunks_embedding
        ON chunks
        USING hnsw (embedding vector_cosine_ops)
        WITH (m = 16, ef_construction = 64)
    """)
